include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_literals_to_create_immutables: ignore


linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false

