name: coredex_pms
description: CoredexPmsApp.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  after_layout: ^1.2.0
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  cloud_firestore: ^4.17.2
  connectivity_plus: ^6.0.3
  dartz: ^0.10.1
  dio: ^5.0.0
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  eva_icons_flutter: ^3.1.0
  event_bus: ^2.0.0
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_image_compress: ^2.2.0
  flutter_native_splash: ^2.3.0
  flutter_svg: ^2.0.3
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.6.1
  iconsax: ^0.0.8
  image: ^4.1.7
  image_picker: ^1.1.1
  isar: 3.1.0
  isar_flutter_libs: 3.1.0
  json_annotation: ^4.8.0
  keyboard_utils_fork: ^0.0.4
  meta: ^1.4.0
  nav: ^1.3.9
  path: ^1.9.0
  path_provider: ^2.1.3
  photo_view: ^0.15.0
  quiver: ^3.2.1
  retrofit: ^4.0.1
  shared_preferences: ^2.0.15
  simple_shadow: ^0.3.1
  syncfusion_flutter_pdfviewer: ^21.2.10
  timeago: ^3.6.1
  url_launcher: ^6.2.6
  validators: ^3.0.0
  velocity_x: ^4.1.0

dev_dependencies:
  build_runner: '2.3.3'
  flutter_lints: ^2.0.0
  flutter_oss_licenses: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: 3.1.0
  json_serializable: ^6.6.1
  mock_web_server: ^5.0.0-nullsafety.1
  retrofit_generator: '5.0.0'
  test: ^1.22.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/logos/
    - assets/image/
    - assets/image/icon/
    - assets/image/stock/
    - assets/image/flag/
    - assets/image/splash/
    - assets/image/darkmode/
    - assets/translations/
    - assets/
